/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#3c4a42",
        "on-secondary-fixed-variant": "#004395",
        "surface-container-low": "#1a1b21",
        "on-error": "#690005",
        "on-primary-container": "#00422b",
        "primary-fixed-dim": "#4edea3",
        "secondary-container": "#0566d9",
        "on-surface": "#e2e2e9",
        "surface-container-high": "#282a2f",
        "surface-tint": "#4edea3",
        "on-tertiary": "#472a00",
        "on-secondary-fixed": "#001a42",
        "on-primary": "#003824",
        "primary-fixed": "#6ffbbe",
        "surface-bright": "#37393f",
        "error-container": "#93000a",
        "surface-container": "#1e1f25",
        "surface": "#111318",
        "error": "#ffb4ab",
        "on-secondary-container": "#e6ecff",
        "surface-dim": "#111318",
        "outline": "#86948a",
        "tertiary-container": "#e29100",
        "secondary-fixed-dim": "#adc6ff",
        "surface-container-highest": "#33353a",
        "on-tertiary-fixed": "#2a1700",
        "inverse-surface": "#e2e2e9",
        "inverse-on-surface": "#2e3036",
        "primary-container": "#10b981",
        "on-surface-variant": "#bbcabf",
        "background": "#111318",
        "tertiary-fixed": "#ffddb8",
        "on-primary-fixed-variant": "#005236",
        "on-tertiary-container": "#523200",
        "surface-variant": "#33353a",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#653e00",
        "on-background": "#e2e2e9",
        "inverse-primary": "#006c49",
        "on-primary-fixed": "#002113",
        "surface-container-lowest": "#0c0e13",
        "secondary": "#adc6ff",
        "primary": "#4edea3",
        "tertiary-fixed-dim": "#ffb95f",
        "on-secondary": "#002e6a",
        "tertiary": "#ffb95f",
        "secondary-fixed": "#d8e2ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "margin": "1.5rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "0.5rem",
        "gutter": "1rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "headline-xl-mobile": ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-lg": ["13px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-xl-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["44px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
